# Generated by Django 5.1.4 on 2025-01-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_course_code_and_more'),
        ('uni_prof', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='professors',
        ),
        migrations.AlterField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='professors', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='universities',
            field=models.ManyToManyField(related_name='professors', to='uni_prof.university'),
        ),
    ]
