# Generated by Django 5.1.4 on 2025-01-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_prof', '0002_remove_university_professors_alter_professor_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='courses',
        ),
    ]
