# Generated by Django 5.1.4 on 2025-01-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_prof', '0005_professor_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
