# Generated by Django 5.1.4 on 2025-01-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_prof', '0006_alter_professor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
