# Generated by Django 5.1.4 on 2025-01-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='public_username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
