# Generated by Django 5.1.4 on 2025-01-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_extendeduser_public_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='public_username',
            field=models.CharField(blank=True, default='default', max_length=20),
            preserve_default=False,
        ),
    ]
