# Generated by Django 5.1.4 on 2025-01-19 16:44

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=30)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_last_modified', models.DateField(auto_now=True)),
                ('course_rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_status', models.IntegerField(choices=[(1, 'OK'), (2, 'UNDER_REVIEW'), (3, 'ARCHIVED'), (4, 'DELETED')], default=courses.models.CourseStatus['UNDER_REVIEW'])),
            ],
        ),
    ]
