# Generated by Django 5.1.4 on 2025-01-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('uni_prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_prof.university'),
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(to='uni_prof.professor'),
        ),
    ]
