# Generated by Django 5.1.4 on 2025-01-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('uni_prof', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_last_modified',
        ),
        migrations.RemoveField(
            model_name='course',
            name='professors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.ManyToManyField(to='uni_prof.professor'),
        ),
    ]
