# Generated by Django 5.1.4 on 2025-01-26 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_course_code_and_more'),
        ('uni_prof', '0003_remove_professor_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(related_name='courses', to='uni_prof.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='uni_prof.university'),
            preserve_default=False,
        ),
    ]
