# Generated by Django 5.1.4 on 2025-01-26 01:22

import courses.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_courses_course_professors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='LOL00000', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='date_last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='review_status',
            field=models.IntegerField(choices=[(1, 'OK'), (2, 'UNDER_REVIEW'), (3, 'ARCHIVED'), (4, 'DELETED')], default=courses.models.CourseStatus['UNDER_REVIEW']),
        ),
    ]
