# Generated by Django 5.1.4 on 2025-01-26 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_code_course_course_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='review_status',
            new_name='course_status',
        ),
    ]
