# Generated by Django 5.1.4 on 2025-01-26 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_review_status_course_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_rating',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
