# Generated by Django 5.1.4 on 2025-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_course_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avg_cognitive_load_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='avg_course_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='avg_delivery_support_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='avg_engagement_enjoyment_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='avg_usefulness_relevance_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
