# Generated by Django 5.1.4 on 2025-02-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_avg_cognitive_load_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.JSONField(default='NA'),
            preserve_default=False,
        ),
    ]
