# Generated by Django 5.1.4 on 2025-01-19 16:44

import django.core.validators
import django.db.models.deletion
import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('rating_left', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('review_status', models.IntegerField(choices=[(1, 'PASSED_REVIEW'), (2, 'UNDER_REVIEW'), (3, 'FAILED_REVIEW')], default=reviews.models.ReviewStatus['UNDER_REVIEW'])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.extendeduser')),
                ('course_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course')),
            ],
        ),
    ]
