# Generated by Django 5.1.4 on 2025-01-26 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_course_code_and_more'),
        ('reviews', '0001_initial'),
        ('users', '0002_alter_extendeduser_public_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='course_reviewed',
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.extendeduser'),
            preserve_default=False,
        ),
    ]
