# Generated by Django 5.1.4 on 2025-01-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='nsfw_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='nsfw_score',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
