# Generated by Django 5.1.4 on 2025-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_nsfw_passed_review_nsfw_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='nsfw_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
